### ISSUE TITLE
Any plans for new release?

### ISSUE THREAD

**Issue by mesb1** [ganskef/mdwiki#4]
Hi.

Not really an issue but more a question.
I was unable to find any other qute wiki for my static hosting than this, but unfortunately original author hasn't built latest fixed 0.6.3, and for some reason my npm installation can't complete with all the required components.

Is it possible to get some release with this fork?

**Comment by ganskef** [comment]
Sorry, I have to fix my GitHub notifications settings ... haven't seen an email (again).

It's my main goal to build MDwiki with recent npm. Please describe your problem. At weekend I will checkout this repo on an other system and try to build it. Maybe I'll find your problem too...

Do you need a GitHub release?

**Comment by mesb1** [comment]
Hi.
Not sure about correct terminology, but I was asking about mdwiki.html build.
Just like it was done already for the 0.6.2 archive a years ago.

A few days later I have reviewed your changes and realize you already applied some fixes, so I don't need to build same requirements like original documents says, but try yours.

But anyway, some other person with less skills or luck might not be able to build mdwiki html by yourself.

**Comment by ganskef** [comment]
I've published a release at <https://github.com/ganskef/mdwiki/releases/tag/0.6.4>. I'm still using this version for weeks and it's good to have an explicit version.

~~Compared to the former MDwiki release tags, I think you simply asked for the release folder and ZIP built with `grunt release`?~~ **Edit:** In the forked tags the release assets are stripped. I had a look at [this](https://github.com/Dynalon/mdwiki/releases/tag/0.6.2) now.

Therefore I should add `npm run release` in package.json to simplify it. For my usage it was completely okay to use the HTML files from the `dist` folder.
